// Error model for the QFinera Fund service/API layer.
//
// Services throw FundError subclasses (or the Phase 1 ForbiddenError /
// InvariantError). API routes convert ANY thrown value into a consistent
// JSON body with toErrorResponse(); unknown errors (including raw database
// errors) are logged server-side and returned as a generic message, so
// internals never reach the client.
import { NextResponse } from "next/server";
import { InvariantError } from "@/lib/accounting/invariants";
import { ForbiddenError } from "@/lib/fund/rbac";

export type FundErrorCode =
  | "VALIDATION"
  | "UNAUTHENTICATED"
  | "FORBIDDEN"
  | "NOT_FOUND"
  | "CONFLICT"
  | "RATE_LIMITED"
  | "INVARIANT"
  | "UNAVAILABLE"
  | "INTERNAL";

export class FundError extends Error {
  constructor(
    readonly code: FundErrorCode,
    message: string,
    readonly status: number,
    readonly fields?: Record<string, string>
  ) {
    super(message);
    this.name = "FundError";
  }
}

export const validationError = (message: string, fields?: Record<string, string>) =>
  new FundError("VALIDATION", message, 400, fields);
export const unauthenticatedError = () => new FundError("UNAUTHENTICATED", "Please sign in to continue.", 401);
export const notFoundError = (what = "Record") => new FundError("NOT_FOUND", `${what} not found.`, 404);
export const conflictError = (message: string) => new FundError("CONFLICT", message, 409);
export const unavailableError = (message = "The Fund workspace is not available right now.") =>
  new FundError("UNAVAILABLE", message, 503);

export type ErrorBody = {
  ok: false;
  error: { code: FundErrorCode; message: string; fields?: Record<string, string> };
};

/** Converts any thrown value to a safe HTTP response. */
export function toErrorResponse(err: unknown): NextResponse<ErrorBody> {
  const respond = (status: number, code: FundErrorCode, message: string, fields?: Record<string, string>) =>
    NextResponse.json<ErrorBody>({ ok: false, error: { code, message, ...(fields ? { fields } : {}) } }, { status });

  if (err instanceof FundError) return respond(err.status, err.code, err.message, err.fields);
  if (err instanceof ForbiddenError) return respond(403, "FORBIDDEN", err.message);
  if (err instanceof InvariantError) {
    // Violation messages are generated by our own accounting code (amounts
    // and counts only), so they are safe and useful to show.
    return respond(409, "INVARIANT", err.violations.map((v) => v.message).join("; "));
  }

  // Unique-violation from a race on a business key (e.g. duplicate UTR,
  // double finalization): report a conflict without exposing the constraint.
  const pgCode = (err as { code?: unknown } | null)?.code;
  if (pgCode === "23505") return respond(409, "CONFLICT", "That record already exists or was already processed.");
  if (pgCode === "23514" || pgCode === "23503" || pgCode === "P0001" || pgCode === "23001") {
    console.error("QFinera Fund: database rule rejected a write:", err);
    return respond(409, "CONFLICT", "That change was rejected because it would break an accounting rule.");
  }

  console.error("QFinera Fund: unexpected error:", err);
  return respond(500, "INTERNAL", "Something went wrong. Please try again.");
}
